### ISSUE TITLE
会崩溃

### ISSUE THREAD

**Issue by yaozifan** [liangdahong/AMLeaksFinder#1]
引入FBRetainCycleDetector后，点击【查看控制器的所有强引用对象】后，会崩溃
![image](https://user-images.githubusercontent.com/15374665/83616531-8ad5f800-a5ba-11ea-9d0c-0b505350987d.png)

**Comment by liangdahong** [comment]
具体什么场景下，控制器是否确认泄露了，可以提供 demo 吗 ？感觉是 FBRetainCycleDetector 的 bug。

**Comment by yaozifan** [comment]
控制器确实泄漏了，使用WebViewJavascriptBridge进行js交互的时候，block导致的循环引用，demo不方便，因为我直接放到我们项目了，哈哈，导致循环引用的代码我截图了
![image](https://user-images.githubusercontent.com/15374665/83703160-45104280-a641-11ea-8236-cf56e643a907.png)

**Comment by liangdahong** [comment]
@yaozifan 如果不集成 FBRetainCycleDetector 不会崩溃吧 😆，理论上 AMLeaksFinder 只负责统计具体的泄露 VC ,点击查看的时候直接使用  FBRetainCycleDetector 来做查找工作，如果不集成 FBRetainCycleDetector 不崩溃的话 可能就是 FBRetainCycleDetector 的问题。

**Comment by yaozifan** [comment]
就是集成了FBRetainCycleDetector都不会崩溃，要点击泄露的控制器，查看强引用的时候才会蹦

**Comment by liangdahong** [comment]
哦哦、在查找 【强引用链】的时候崩溃，可以到 FBRetainCycleDetector 提 issues 看看。
