### ISSUE TITLE
能否添加一个开关，类似MLeaksFinder那样，根据具体情况，决定是否启用工具。

### ISSUE THREAD

**Issue by xjh093** [liangdahong/AMLeaksFinder#10]
MLeaksFinder 有个宏定义，可以手动修改，来启用与关闭工具。
有的情况，确实是不需要开启工具。

**Comment by liangdahong** [comment]
推荐使用 pod 导入➕ debug 标识，至于加开关我考虑一下，以及白名单功能等，感觉可以添加，或者你有好想法可以提下 PR。🤣

**Comment by xjh093** [comment]
我的意思是，开发阶段，都是 DEBUG 模式，如果没有开关，要关闭的话，每次都要去执行 pod 命令了，非常不效率。

**Comment by liangdahong** [comment]
明白，我参考下 ml。

**Comment by liangdahong** [comment]
@xjh093 已增加宏开关 https://github.com/liangdahong/AMLeaksFinder/releases/tag/2.1.2  
- 参考文档1：https://github.com/liangdahong/AMLeaksFinder#%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8
- 参考代码：https://github.com/liangdahong/AMLeaksFinder/blob/master/AMLeaksFinder/AMLeaksFinder.h

**Comment by xjh093** [comment]
nice~🥳🥳

**Comment by mlch911** [comment]
现在这个开关必须要改代码才能控制，能否把这个宏改成 BOOL？

**Comment by xjh093** [comment]
你还想实时控制？

**Comment by mlch911** [comment]
> 你还想实时控制？

已经改好了，提了PR #20

**Comment by liangdahong** [comment]
@xjh093 添加的功能是外部可以控制 【泄漏提示UI】 的显示和隐藏，底层泄漏数据正常运转。
