### ISSUE TITLE
引入FBRetainCycleDetector后查看不了强引链

### ISSUE THREAD

**Issue by Detachments** [liangdahong/AMLeaksFinder#15]
![share](https://user-images.githubusercontent.com/16662408/160316101-d4c831ad-70f1-47ff-b6f5-d6cc4aa965d9.jpg)

**Comment by liangdahong** [comment]
可能是 FBRetainCycleDetector 未检测到，FBRetainCycleDetector 主要是辅助排查，如无法排查建议人工排查。

**Comment by Detachments** [comment]
收到~~
