### ISSUE TITLE
UITextField误报？

### ISSUE THREAD

**Issue by viihua** [liangdahong/AMLeaksFinder#18]
在一个VC上TableViewCell上添加UITextField，初始化时设置UITextField的text的值 ，后续调用UITextField修改，pop后提示UITextField泄漏。再次进入又销毁了。

**Comment by liangdahong** [comment]
系统原因（特意常驻了），
可以配下 view 忽略名单
```
 @property (class) NSSet <NSString *> * _Nullable ignoreViewClassNameSet; 
```
