### ISSUE TITLE
需求：UIView泄漏检测

### ISSUE THREAD

**Issue by cddjr** [liangdahong/AMLeaksFinder#2]
目前只能检测到VC的泄漏，希望能恢复MLeaksFinder中的这一功能

**Comment by liangdahong** [comment]
@cddjr 你好，目前正在构思 UIView 这块的泄漏监控。

**Comment by liangdahong** [comment]
@cddjr  已初步支持 UIView 的内存泄露监控。
https://github.com/liangdahong/AMLeaksFinder/releases
