### ISSUE TITLE
建议：没有泄漏的时候用绿色字体显示数量

### ISSUE THREAD

**Issue by cddjr** [liangdahong/AMLeaksFinder#3]
目前有没有泄漏都是红色显示数量，体验不太好

**Comment by liangdahong** [comment]
@cddjr  建议不错，感谢。

**Comment by liangdahong** [comment]
已微调 UI 😄。
<img  width="20%" src="https://user-images.githubusercontent.com/12118567/94993941-fd85cd00-05c6-11eb-8c3d-7d07bef59c7c.png"/>
<img  width="20%" src="https://user-images.githubusercontent.com/12118567/94993950-0d9dac80-05c7-11eb-99ae-f023f7d3b5b8.png"/>
