### ISSUE TITLE
对比MLeakFinder

### ISSUE THREAD

**Issue by helinyu** [liangdahong/AMLeaksFinder#4]
问一下， 你这个和MLeakFinder 有什么区别？ 或者说有什么优势？

**Comment by liangdahong** [comment]
1. 数据可视化，做到心中有数，脑中有图；
2. 持续跟踪控制器释放情况，MLeakFinder 没持续跟踪，只是延时一段时间未释放就认为泄漏，其实有一些场景不一定准；
3. 具体泄漏检测逻辑类似，对具体泄漏判断有一些区别，当然也参考了一些其思想，非常感谢 MLeakFinder 。

**Comment by helinyu** [comment]
Pod::Spec.new do |s|
s.name         = 'AMLeaksFinder'
s.version      = '1.2.9'
s.summary      = 'A small tool for automatically detecting the [controller memory leak] in the project'
s.homepage     = 'https://github.com/liangdahong/AMLeaksFinder'
s.license      = 'MIT'
s.authors      = {'梁大红' => 'ios@liangdahong.com'}
s.platform     = :ios, '8.0'
s.source       = {:git => 'https://github.com/liangdahong/AMLeaksFinder.git', :tag => s.version}
s.source_files = 'AMLeaksFinder/**/*.{h,m}'
s.resource     = 'AMLeaksFinder/**/*.{bundle,xib}'
s.dependency 'FBRetainCycleDetector'
s.requires_arc = true
end

这个地方可以依赖： s.dependency 'FBRetainCycleDetector'

**Comment by liangdahong** [comment]
额额，好建议，但感觉部分用户不喜欢引入 FBRetainCycleDetector，所以我想把控制权给使用者。
