### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Demonsword27** [liangdahong/AMLeaksFinder#7]
I used a singleton example and found that there was a problem

**Comment by liangdahong** [comment]
What is the specific problem? If the controller is a singleton, its leakage may be detected, and you can click Ignore to deal with it.

**Comment by Demonsword27** [comment]
嗷，没主意，你有一个标记忽略的方法。不过基于你目前的思路，我也暂时想不到通过非手动的方式去排除，您有思路吗。

**Comment by liangdahong** [comment]
可以考虑从代码层面来添加白名单，但我个人对这种方案不是特别感兴趣，这样会污染代码【后面可能会添加】，我想做纯净的 debug 工具，同时单例不是最好的设计方案。

**Comment by Demonsword27** [comment]
好的，感谢解答
