### ISSUE TITLE
使用第三方库 LCActionSheet 后，之前 window 的根视图，全部泄露！

### ISSUE THREAD

**Issue by xjh093** [liangdahong/AMLeaksFinder#8]
LCActionSheet 内部有使用自己的 UIWindow 来展示控制器
LCActionSheet 关闭后，原 UIWindow 的根视图及子视图，被标记为泄露。

**Comment by liangdahong** [comment]
@xjh093 有 demo 吗 ？

**Comment by xjh093** [comment]
抽空写个 demo 再试试看

**Comment by xjh093** [comment]
Demo 已发送到你的邮箱
测试了其他第三方库，内部有使用自己的 UIWindow 来展示控制器，则会有此Bug

**Comment by liangdahong** [comment]
好的  已收到，晚点看看，感谢。

**Comment by liangdahong** [comment]
在 https://github.com/liangdahong/AMLeaksFinder/commit/dfa8c15c78e2b0e16c3d7f917f0e3c2586173acb 已处理，感谢。

**Comment by xjh093** [comment]
OK!
Well done!
