### ISSUE TITLE
不能用于swift 吗？

### ISSUE THREAD

**Issue by DuShuYuan** [liangdahong/AMLeaksFinder#9]
我用swift写了内存泄漏的代码，但是没有检测出来啊
```
        btn.onClick {
            self.navigationController?.popViewController(animated: true)
        }
```

**Comment by liangdahong** [comment]
支持 swift，self 有直接或间接持有 btn 吗？，而且是 self 在退出的时候才会检查到，在 self 里 deinit log 看看是否有释放，或者帮整理下 demo。

**Comment by DuShuYuan** [comment]
> 支持 swift，self 有直接或间接持有 btn 吗？，而且是 self 在退出的时候才会检查到，在 self 里 deinit log 看看是否有释放，或者帮整理下 demo。

```

class TestView: UIViewController {
    init() {
        super.init(nibName: nil, bundle: nil)
        log.error("init=====")
    }
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    deinit {
        log.error("deinit=====")
    }
    let mBtn = MButton()
    override func viewDidLoad() {
        mBtn.setTitle("有内存泄漏的页面", for: .normal)
        view.addSubview(mBtn)
        mBtn.snp.makeConstraints { make in
            make.center.size.equalToSuperview()
        }
//        weak var wSelf = self
        mBtn.onClick {
            self.navigationController?.popViewController(animated: true)
//            wSelf?.navigationController?.popViewController(animated: true)
        }
    }

}

```

这样写没有走 deinit()，也没有检测到内存泄漏，而且VC数量始终都是1不变
<img width="585" alt="WeChat631a8d7b2280ce73c42202fb4611f8be" src="https://user-images.githubusercontent.com/11830896/123585266-7bed6380-d815-11eb-9485-cd8cb58826de.png">
<img width="585" alt="WeChat670cc47b1e8365f33c7a25d043fd151b" src="https://user-images.githubusercontent.com/11830896/123585289-8ad41600-d815-11eb-945d-ab3a49444c85.png">

**Comment by liangdahong** [comment]
@DuShuYuan 知道原因了，是因为你的控制器里的 `viewDidLoad `方法没有调 super. viewDidLoad() 导致的，所以没办法 hook 到你自定义的 VC 的 viewDidLoad 方法，建议还是调一下 super ，同时我也考虑怎么优化，感谢你的反馈。

![image](https://user-images.githubusercontent.com/12118567/123664915-60607800-d86a-11eb-80d4-8bafb4a5878e.png)

**Comment by DuShuYuan** [comment]
> @DuShuYuan 知道原因了，是因为你的控制器里的 `viewDidLoad `方法没有调 super. viewDidLoad() 导致的，所以没办法 hook 到你自定义的 VC 的 viewDidLoad 方法，建议还是调一下 super ，同时我也考虑怎么优化，感谢你的反馈。
> 
> ![image](https://user-images.githubusercontent.com/12118567/123664915-60607800-d86a-11eb-80d4-8bafb4a5878e.png)

多谢！调用了super就可以了！
